VERSION="2.0"

[[CURRENCIES]]
code="MYTT2"
issuer="GCLXICPGTEPEM3E5BMKWORTJJ5SVBGICROPZWZZHVZMPWQNREJOFFW7Z"
name="MYTOKEN"
desc="MYTOKEN is a Pi Testnet token created for learning and development purposes."
image="https://vimalpi.github.io/PiToken/logo.png"
status="live"
display_decimals=7
