# Pi configuration

# The title of your site
title = "Your Site Title"

# The base URL of your site
base_url = "https://vimalpi.github.io/PiToken/"

# The author of the site
author = "Your Name"

# The theme of your site
theme = "default"

# Additional settings can be added as needed
